### ISSUE TITLE
[BUG]  java develpment mode  error

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [theaidenlab/juicebox#1010]
hi Juicerbox team,
i am trying to use juicer pre for juicerbox files.
i am facing this error.
please anybody can guide me. Thanks

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-05-23T06:00:01,593] [Globals.java:138] [main] Development mode is enabled.

**Comment by sa501428** [comment]
This is a warning but should not cause anything to fail/ exit. What are you
trying to do?

**Comment by ABDULLAHGUJJAR** [comment]
Hi Dear Saad,
I am getting this error, after that I am not getting output for juicebox
[04/55f2c5] process > PRINT_VERSIONS     [100%] 1 of 1, cached: 1 ✔
[a1/8933f7] process > SAMTOOLS_FAIDX (1) [100%] 1 of 1, cached: 1 ✔
[62/69386f] process > CHROMAP_INDEX (1)  [100%] 1 of 1, cached: 1 ✔
[ef/d55389] process > CHROMAP_ALIGN (1)  [100%] 1 of 1, cached: 1 ✔
[15/78602f] process > YAHS_SCAFFOLD (1)  [100%] 1 of 1, cached: 1 ✔
[78/3fede9] process > JUICER_PRE (1)     [100%] 1 of 1, failed: 1 ✘
[24/196ac9] process > ASSEMBLY_STATS (1) [100%] 1 of 1, cached: 1 ✔
Error executing process > 'JUICER_PRE (1)'

Caused by:
  Process `JUICER_PRE (1)` terminated with an error exit status (1)

Command executed:

  juicer pre -a -o out_JBAT         yahs.out.bin         yahs.out_scaffolds_final.agp         contigs.fa.fai

  asm_size=$(awk '{s+=$2} END{print s}' contigs.fa.fai)
  java -Xmx36G -jar /scratch/project/qaafi-cnafs/abdullah.WRB.HASLR/check/juicer_tools_1.22.01.jar         pre out_JBAT.txt out_JBAT.hic <(echo "assembly ${asm_size}")

Command exit status:
  1

Command output:
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-05-24T20:17:23,608]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  .

Command error:
  [I::main_pre] make juicer pre input from BIN file yahs.out.bin
  [I::make_juicer_pre_file_from_bin] 195631424 read pairs processed
  [I::main_pre] genome size: 403126564
  [I::main_pre] scale factor: 1
  [I::main_pre] chromosome sizes for juicer_tools pre -
  PRE_C_SIZE: assembly 403126564
  [I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre out_JBAT.txt out_JBAT.hic <(echo "assembly 403126564")
  [I::main_pre] Version: 1.1
  [I::main_pre] CMD: juicer pre -a -o out_JBAT yahs.out.bin yahs.out_scaffolds_final.agp contigs.fa.fai
  [I::main_pre] Real time: 33.716 sec; CPU: 33.412 sec; Peak RSS: 0.002 GB
  WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
  WARN [2023-05-24T20:17:23,608]  [Globals.java:138] [main]  Development mode is enabled
  Using 1 CPU thread(s)
  Not including fragment map
  Start preprocess
  Writing header
  Writing body
  .Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
        at java.base/java.lang.String.substring(String.java:1879)
        at java.base/java.lang.String.subSequence(String.java:1913)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1271)
        at java.base/java.lang.String.split(String.java:2317)
        at java.base/java.lang.String.split(String.java:2364)
        at juicebox.tools.clt.JuiceboxCLT.splitToList(JuiceboxCLT.java:47)
        at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:125)
  rk dirat juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:287)
  /scratat juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:673)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:425)
  p: youat juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:139)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)

Work dir:
  /scratch/project_mnt/S0030/abdullah.WRB.HASLR/check/work/78/3fede93453ae13cce8532ff29fe7a6

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

I am using this nextflow script

https://github.com/WarrenLab/hic-scaffolding-nf.<https://github.com/WarrenLab/hic-scaffolding-nf>

Please check it.
Thank you so much
Regards
Abdullah
